# Generated by Django 5.0.6 on 2025-04-02 08:51

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dodavatele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dodavatel', models.CharField(max_length=100, verbose_name='Dodavatel')),
                ('kontakt', models.CharField(max_length=100, null=True, verbose_name='Kontaktní osoba')),
                ('email', models.EmailField(max_length=100, null=True, verbose_name='E-mail')),
                ('telefon', models.CharField(max_length=20, null=True, verbose_name='Telefon')),
                ('jazyk', models.CharField(choices=[('CZ', 'Český'), ('SK', 'Slovenský'), ('DE', 'Německý'), ('EN', 'Anglický')], default='CZ', max_length=2, null=True, verbose_name='Jazyk')),
            ],
            options={
                'verbose_name_plural': 'Dodavatelé',
            },
        ),
        migrations.CreateModel(
            name='Sklad',
            fields=[
                ('evidencni_cislo', models.AutoField(primary_key=True, serialize=False, verbose_name='Evidenční číslo')),
                ('interne_cislo', models.IntegerField(null=True, verbose_name='Číslo karty')),
                ('objednano', models.CharField(blank=True, max_length=100, null=True, verbose_name='Objednáno?')),
                ('nazev_dilu', models.CharField(max_length=100, verbose_name='Název dílu')),
                ('min_mnozstvi_ks', models.PositiveIntegerField(default=0, verbose_name='Minimum')),
                ('mnozstvi', models.PositiveIntegerField(default=0, verbose_name='Množství')),
                ('jednotky', models.CharField(choices=[('ks', 'kus'), ('kg', 'kilogram'), ('pár', 'pár'), ('l', 'litr'), ('m', 'metr'), ('balení', 'balení')], default='ks', max_length=10, verbose_name='Jednotky')),
                ('umisteni', models.CharField(max_length=25, null=True, verbose_name='Umístění')),
                ('dodavatel', models.CharField(blank=True, max_length=70, null=True, verbose_name='Dodavatel')),
                ('datum_nakupu', models.DateField(blank=True, null=True, verbose_name='Datum nákupu')),
                ('cislo_objednavky', models.CharField(blank=True, max_length=20, null=True, verbose_name='Číslo objednávky')),
                ('jednotkova_cena_eur', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='EUR/jednotka')),
                ('celkova_cena_eur', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Celkem EUR')),
                ('poznamka', models.CharField(blank=True, max_length=200, null=True, verbose_name='Poznámka')),
                ('ucetnictvi', models.BooleanField(default=True, verbose_name='Účetnictví')),
                ('kriticky_dil', models.BooleanField(default=False, verbose_name='Kritický díl')),
            ],
            options={
                'verbose_name_plural': 'Skladové položky',
                'ordering': ['-evidencni_cislo'],
            },
        ),
        migrations.CreateModel(
            name='Zarizeni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod_zarizeni', models.CharField(max_length=10, null=True, verbose_name='Kód zařízení')),
                ('nazev_zarizeni', models.CharField(max_length=100, null=True, verbose_name='Název zařízení')),
                ('umisteni', models.CharField(max_length=20, null=True, verbose_name='Umístění')),
                ('typ_zarizeni', models.CharField(max_length=100, null=True, verbose_name='Typ zařízení')),
            ],
            options={
                'verbose_name_plural': 'Zařízení',
            },
        ),
        migrations.CreateModel(
            name='HistoricalSklad',
            fields=[
                ('evidencni_cislo', models.IntegerField(blank=True, db_index=True, verbose_name='Evidenční číslo')),
                ('interne_cislo', models.IntegerField(null=True, verbose_name='Číslo karty')),
                ('objednano', models.CharField(blank=True, max_length=100, null=True, verbose_name='Objednáno?')),
                ('nazev_dilu', models.CharField(max_length=100, verbose_name='Název dílu')),
                ('min_mnozstvi_ks', models.PositiveIntegerField(default=0, verbose_name='Minimum')),
                ('mnozstvi', models.PositiveIntegerField(default=0, verbose_name='Množství')),
                ('jednotky', models.CharField(choices=[('ks', 'kus'), ('kg', 'kilogram'), ('pár', 'pár'), ('l', 'litr'), ('m', 'metr'), ('balení', 'balení')], default='ks', max_length=10, verbose_name='Jednotky')),
                ('umisteni', models.CharField(max_length=25, null=True, verbose_name='Umístění')),
                ('dodavatel', models.CharField(blank=True, max_length=70, null=True, verbose_name='Dodavatel')),
                ('datum_nakupu', models.DateField(blank=True, null=True, verbose_name='Datum nákupu')),
                ('cislo_objednavky', models.CharField(blank=True, max_length=20, null=True, verbose_name='Číslo objednávky')),
                ('jednotkova_cena_eur', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='EUR/jednotka')),
                ('celkova_cena_eur', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Celkem EUR')),
                ('poznamka', models.CharField(blank=True, max_length=200, null=True, verbose_name='Poznámka')),
                ('ucetnictvi', models.BooleanField(default=True, verbose_name='Účetnictví')),
                ('kriticky_dil', models.BooleanField(default=False, verbose_name='Kritický díl')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical sklad',
                'verbose_name_plural': 'historical Skladové položky',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Poptavky',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_vytvoreni', models.DateTimeField(auto_now_add=True, verbose_name='Datum vytvoření')),
                ('stav', models.CharField(choices=[('Tvorba', 'Ve tvorbě'), ('Poptáno', 'Poptáno'), ('Uzavřeno', 'Uzavřeno')], default='Tvorba', max_length=10, verbose_name='Stav poptávky')),
                ('dodavatel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poptavky_dodavatele', to='hpm_sklad.dodavatele', verbose_name='Dodavatel')),
            ],
            options={
                'verbose_name': 'Poptávka',
                'verbose_name_plural': 'Poptávky',
            },
        ),
        migrations.CreateModel(
            name='PoptavkaVarianty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mnozstvi', models.PositiveIntegerField(verbose_name='Množství')),
                ('jednotky', models.CharField(choices=[('ks', 'kus'), ('kg', 'kilogram'), ('pár', 'pár'), ('l', 'litr'), ('m', 'metr'), ('balení', 'balení')], max_length=10, verbose_name='Jednotky')),
                ('poptavka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poptavka', to='hpm_sklad.poptavky', verbose_name='Poptávka')),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ucetnictvi', models.BooleanField(verbose_name='Účetnictví')),
                ('interne_cislo', models.IntegerField(null=True, verbose_name='Číslo karty')),
                ('objednano', models.CharField(blank=True, max_length=100, null=True, verbose_name='Objednáno?')),
                ('nazev_dilu', models.CharField(db_index=True, max_length=100, verbose_name='Název dílu')),
                ('zmena_mnozstvi', models.IntegerField(verbose_name='Změna množství')),
                ('mnozstvi', models.PositiveIntegerField(verbose_name='Množství')),
                ('jednotky', models.CharField(choices=[('ks', 'kus'), ('kg', 'kilogram'), ('pár', 'pár'), ('l', 'litr'), ('m', 'metr'), ('balení', 'balení')], default='ks', max_length=10, verbose_name='Jednotky')),
                ('typ_operace', models.CharField(choices=[('PŘÍJEM', 'Příjem'), ('VÝDEJ', 'Výdej')], max_length=10, null=True, verbose_name='Typ operace')),
                ('pouzite_zarizeni', models.CharField(max_length=70, null=True, verbose_name='Pro zařízení')),
                ('umisteni', models.CharField(max_length=25, verbose_name='Umístění')),
                ('dodavatel', models.CharField(max_length=70, verbose_name='Dodavatel')),
                ('datum_vydeje', models.DateField(blank=True, null=True, verbose_name='Datum výdeje')),
                ('datum_nakupu', models.DateField(blank=True, null=True, verbose_name='Datum nákupu')),
                ('cislo_objednavky', models.CharField(blank=True, max_length=20, null=True, verbose_name='Číslo objednávky')),
                ('jednotkova_cena_eur', models.FloatField(default=0.0, verbose_name='EUR/jednotka')),
                ('celkova_cena_eur', models.FloatField(default=0.0, verbose_name='Celkem EUR')),
                ('cas_vytvoreni', models.DateTimeField(auto_now_add=True, verbose_name='Čas vytvoření')),
                ('typ_udrzby', models.CharField(choices=[('Reaktivní', 'Reaktivní'), ('Preventivní', 'Preventivní'), ('Prediktivní', 'Prediktivní'), ('Inventura', 'Inventurní rozdíl')], max_length=20, null=True, verbose_name='Typ údržby')),
                ('poznamka', models.CharField(blank=True, max_length=200, null=True, verbose_name='Poznámka')),
                ('operaci_provedl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Operaci provedl')),
                ('evidencni_cislo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hpm_sklad.sklad', verbose_name='Evidenční číslo')),
            ],
            options={
                'verbose_name_plural': 'Auditovací logy',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Varianty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev_varianty', models.CharField(max_length=255, verbose_name='Název varianty')),
                ('cislo_varianty', models.CharField(max_length=255, null=True, verbose_name='Číslo varianty')),
                ('jednotkova_cena_eur', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='EUR/jednotka')),
                ('dodaci_lhuta', models.PositiveIntegerField(verbose_name='Dodací lhůta')),
                ('min_obj_mnozstvi', models.PositiveIntegerField(verbose_name='Min. obj. množství')),
                ('dodavatel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='varianty_dodavatele', to='hpm_sklad.dodavatele', verbose_name='Dodavatel')),
                ('sklad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='varianty_skladu', to='hpm_sklad.sklad', verbose_name='Skladová položka')),
            ],
            options={
                'verbose_name': 'Varianta',
                'verbose_name_plural': 'Varianty',
            },
        ),
        migrations.AddField(
            model_name='poptavky',
            name='varianty',
            field=models.ManyToManyField(through='hpm_sklad.PoptavkaVarianty', to='hpm_sklad.varianty'),
        ),
        migrations.AddField(
            model_name='poptavkavarianty',
            name='varianta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='varianta', to='hpm_sklad.varianty', verbose_name='Varianta'),
        ),
        migrations.CreateModel(
            name='SkladZarizeni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sklad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hpm_sklad.sklad', verbose_name='Skladová položka')),
                ('zarizeni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hpm_sklad.zarizeni', verbose_name='Zařízení')),
            ],
            options={
                'verbose_name_plural': 'Skladové položky - Zařízení',
                'db_table': 'hpm_sklad_sklad_zarizeni',
                'unique_together': {('sklad', 'zarizeni')},
            },
        ),
        migrations.AddField(
            model_name='sklad',
            name='zarizeni',
            field=models.ManyToManyField(blank=True, through='hpm_sklad.SkladZarizeni', to='hpm_sklad.zarizeni', verbose_name='Zařízení'),
        ),
    ]
