# Generated by Django 5.0.4 on 2024-04-22 18:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sklad',
            fields=[
                ('evidencni_cislo', models.IntegerField(db_column='Evidencni_cislo', primary_key=True, serialize=False)),
                ('ucetnictvi', models.BooleanField(db_column='Ucetnictvi', default=False)),
                ('kriticky_dil', models.BooleanField(db_column='Kriticky_dil', default=False)),
                ('interne_cislo', models.IntegerField(db_column='Interne_cislo')),
                ('min_mnozstvi_ks', models.IntegerField(db_column='Min_Mnozstvi_ks', validators=[django.core.validators.MinValueValidator(0)])),
                ('objednano', models.CharField(blank=True, db_column='Objednano', max_length=100, null=True)),
                ('nazev_dilu', models.CharField(db_column='Nazev_dilu', max_length=100)),
                ('mnozstvi_ks_m_l', models.IntegerField(db_column='Mnozstvi_ks_m_l', validators=[django.core.validators.MinValueValidator(0)])),
                ('jednotky', models.CharField(choices=[('ks', 'kusy'), ('kg', 'kilogramy'), ('par', 'páry'), ('l', 'litry'), ('m', 'metry'), ('baleni', 'balení')], db_column='Jednotky', default='ks', max_length=10)),
                ('umisteni', models.CharField(db_column='Umisteni', max_length=100)),
                ('dodavatel', models.CharField(db_column='Dodavatel', max_length=100, null=True)),
                ('datum_nakupu', models.DateField(blank=True, db_column='Datum_nakupu', null=True)),
                ('cislo_objednavky', models.CharField(db_column='Cislo_objednavky', max_length=20, null=True)),
                ('jednotkova_cena_eur', models.FloatField(db_column='Jednotkova_cena_EUR', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('celkova_cena_eur', models.FloatField(db_column='Celkova_cena_EUR', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('poznamka', models.CharField(blank=True, db_column='Poznamka', max_length=200, null=True)),
                ('hsh', models.BooleanField(db_column='HSH', default=False)),
                ('tq8', models.BooleanField(db_column='TQ8', default=False)),
                ('tqf_xl1', models.BooleanField(db_column='TQF_XL1', default=False)),
                ('tqf_xl2', models.BooleanField(db_column='TQF_XL2', default=False)),
                ('dc_xl', models.BooleanField(db_column='DC_XL', default=False)),
                ('dac_xl1_2', models.BooleanField(db_column='DAC_XL1/2', default=False)),
                ('dl_xl', models.BooleanField(db_column='DL_XL', default=False)),
                ('dac', models.BooleanField(db_column='DAC', default=False)),
                ('lac_1', models.BooleanField(db_column='LAC_1', default=False)),
                ('lac_2', models.BooleanField(db_column='LAC_2', default=False)),
                ('ipsen_ene', models.BooleanField(db_column='IPSEN_ENE', default=False)),
                ('hsh_ene', models.BooleanField(db_column='HSH_ENE', default=False)),
                ('xl_ene1', models.BooleanField(db_column='XL_ENE1', default=False)),
                ('xl_ene2', models.BooleanField(db_column='XL_ENE2', default=False)),
                ('ipsen_w', models.BooleanField(db_column='IPSEN_W', default=False)),
                ('hsh_w', models.BooleanField(db_column='HSH_W', default=False)),
                ('kw', models.BooleanField(db_column='KW', default=False)),
                ('kw1', models.BooleanField(db_column='KW1', default=False)),
                ('kw2', models.BooleanField(db_column='KW2', default=False)),
                ('kw3', models.BooleanField(db_column='KW3', default=False)),
                ('mikrof', models.BooleanField(db_column='MIKROF', default=False)),
            ],
        ),
    ]
