# Generated by Django 5.0.6 on 2025-04-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hpm_sklad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsklad',
            name='dac',
            field=models.BooleanField(default=False, verbose_name='DAC'),
        ),
        migrations.AddField(
            model_name='historicalsklad',
            name='dac_xl1_2',
            field=models.BooleanField(default=False, verbose_name='DAC XL1-2'),
        ),
        migrations.AddField(
            model_name='historicalsklad',
            name='dc_xl',
            field=models.BooleanField(default=False, verbose_name='DC XL'),
        ),
        migrations.AddField(
            model_name='historicalsklad',
            name='dl_xl',
            field=models.BooleanField(default=False, verbose_name='DL XL'),
        ),
        migrations.AddField(
            model_name='historicalsklad',
            name='hsh',
            field=models.BooleanField(default=False, verbose_name='HSH'),
        ),
        migrations.AddField(
            model_name='historicalsklad',
            name='hsh_ene',
            field=models.BooleanField(default=False, verbose_name='HSH ENE'),
        ),
        migrations.AddField(
            model_name='historicalsklad',
            name='hsh_w',
            field=models.BooleanField(default=False, verbose_name='HSH W'),
        ),
        migrations.AddField(
            model_name='historicalsklad',
            name='ipsen_ene',
            field=models.BooleanField(default=False, verbose_name='IPSEN ENE'),
        ),
        migrations.AddField(
            model_name='historicalsklad',
            name='ipsen_w',
            field=models.BooleanField(default=False, verbose_name='IPSEN W'),
        ),
        migrations.AddField(
            model_name='historicalsklad',
            name='kw',
            field=models.BooleanField(default=False, verbose_name='KW'),
        ),
        migrations.AddField(
            model_name='historicalsklad',
            name='kw1',
            field=models.BooleanField(default=False, verbose_name='KW 1'),
        ),
        migrations.AddField(
            model_name='historicalsklad',
            name='kw2',
            field=models.BooleanField(default=False, verbose_name='KW 2'),
        ),
        migrations.AddField(
            model_name='historicalsklad',
            name='kw3',
            field=models.BooleanField(default=False, verbose_name='KW 3'),
        ),
        migrations.AddField(
            model_name='historicalsklad',
            name='lac_1',
            field=models.BooleanField(default=False, verbose_name='LAC 1'),
        ),
        migrations.AddField(
            model_name='historicalsklad',
            name='lac_2',
            field=models.BooleanField(default=False, verbose_name='LAC 2'),
        ),
        migrations.AddField(
            model_name='historicalsklad',
            name='mikrof',
            field=models.BooleanField(default=False, verbose_name='MIKROF'),
        ),
        migrations.AddField(
            model_name='historicalsklad',
            name='q8',
            field=models.BooleanField(default=False, verbose_name='TQ8'),
        ),
        migrations.AddField(
            model_name='historicalsklad',
            name='tqf_xl1',
            field=models.BooleanField(default=False, verbose_name='TQF XL1'),
        ),
        migrations.AddField(
            model_name='historicalsklad',
            name='tqf_xl2',
            field=models.BooleanField(default=False, verbose_name='TQF XL2'),
        ),
        migrations.AddField(
            model_name='historicalsklad',
            name='xl_ene1',
            field=models.BooleanField(default=False, verbose_name='XL ENE1'),
        ),
        migrations.AddField(
            model_name='historicalsklad',
            name='xl_ene2',
            field=models.BooleanField(default=False, verbose_name='XL ENE2'),
        ),
        migrations.AddField(
            model_name='sklad',
            name='dac',
            field=models.BooleanField(default=False, verbose_name='DAC'),
        ),
        migrations.AddField(
            model_name='sklad',
            name='dac_xl1_2',
            field=models.BooleanField(default=False, verbose_name='DAC XL1-2'),
        ),
        migrations.AddField(
            model_name='sklad',
            name='dc_xl',
            field=models.BooleanField(default=False, verbose_name='DC XL'),
        ),
        migrations.AddField(
            model_name='sklad',
            name='dl_xl',
            field=models.BooleanField(default=False, verbose_name='DL XL'),
        ),
        migrations.AddField(
            model_name='sklad',
            name='hsh',
            field=models.BooleanField(default=False, verbose_name='HSH'),
        ),
        migrations.AddField(
            model_name='sklad',
            name='hsh_ene',
            field=models.BooleanField(default=False, verbose_name='HSH ENE'),
        ),
        migrations.AddField(
            model_name='sklad',
            name='hsh_w',
            field=models.BooleanField(default=False, verbose_name='HSH W'),
        ),
        migrations.AddField(
            model_name='sklad',
            name='ipsen_ene',
            field=models.BooleanField(default=False, verbose_name='IPSEN ENE'),
        ),
        migrations.AddField(
            model_name='sklad',
            name='ipsen_w',
            field=models.BooleanField(default=False, verbose_name='IPSEN W'),
        ),
        migrations.AddField(
            model_name='sklad',
            name='kw',
            field=models.BooleanField(default=False, verbose_name='KW'),
        ),
        migrations.AddField(
            model_name='sklad',
            name='kw1',
            field=models.BooleanField(default=False, verbose_name='KW 1'),
        ),
        migrations.AddField(
            model_name='sklad',
            name='kw2',
            field=models.BooleanField(default=False, verbose_name='KW 2'),
        ),
        migrations.AddField(
            model_name='sklad',
            name='kw3',
            field=models.BooleanField(default=False, verbose_name='KW 3'),
        ),
        migrations.AddField(
            model_name='sklad',
            name='lac_1',
            field=models.BooleanField(default=False, verbose_name='LAC 1'),
        ),
        migrations.AddField(
            model_name='sklad',
            name='lac_2',
            field=models.BooleanField(default=False, verbose_name='LAC 2'),
        ),
        migrations.AddField(
            model_name='sklad',
            name='mikrof',
            field=models.BooleanField(default=False, verbose_name='MIKROF'),
        ),
        migrations.AddField(
            model_name='sklad',
            name='q8',
            field=models.BooleanField(default=False, verbose_name='TQ8'),
        ),
        migrations.AddField(
            model_name='sklad',
            name='tqf_xl1',
            field=models.BooleanField(default=False, verbose_name='TQF XL1'),
        ),
        migrations.AddField(
            model_name='sklad',
            name='tqf_xl2',
            field=models.BooleanField(default=False, verbose_name='TQF XL2'),
        ),
        migrations.AddField(
            model_name='sklad',
            name='xl_ene1',
            field=models.BooleanField(default=False, verbose_name='XL ENE1'),
        ),
        migrations.AddField(
            model_name='sklad',
            name='xl_ene2',
            field=models.BooleanField(default=False, verbose_name='XL ENE2'),
        ),
    ]
