# Generated by Django 5.0.4 on 2024-05-07 20:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hpm_sklad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sklad',
            name='celkova_cena_eur',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Celkem EUR'),
        ),
        migrations.AlterField(
            model_name='sklad',
            name='cislo_objednavky',
            field=models.CharField(max_length=20, null=True, verbose_name='Číslo objednávky'),
        ),
        migrations.AlterField(
            model_name='sklad',
            name='dac',
            field=models.BooleanField(default=False, verbose_name='DAC'),
        ),
        migrations.AlterField(
            model_name='sklad',
            name='dac_xl1_2',
            field=models.BooleanField(default=False, verbose_name='DAC XL1/2'),
        ),
        migrations.AlterField(
            model_name='sklad',
            name='datum_nakupu',
            field=models.DateField(blank=True, null=True, verbose_name='Datum nákupu'),
        ),
        migrations.AlterField(
            model_name='sklad',
            name='dc_xl',
            field=models.BooleanField(default=False, verbose_name='DC XL'),
        ),
        migrations.AlterField(
            model_name='sklad',
            name='dl_xl',
            field=models.BooleanField(default=False, verbose_name='DL XL'),
        ),
        migrations.AlterField(
            model_name='sklad',
            name='dodavatel',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Dodavatel'),
        ),
        migrations.AlterField(
            model_name='sklad',
            name='evidencni_cislo',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Evidenční číslo'),
        ),
        migrations.AlterField(
            model_name='sklad',
            name='hsh',
            field=models.BooleanField(default=False, verbose_name='HSH'),
        ),
        migrations.AlterField(
            model_name='sklad',
            name='hsh_ene',
            field=models.BooleanField(default=False, verbose_name='HSH ENE'),
        ),
        migrations.AlterField(
            model_name='sklad',
            name='hsh_w',
            field=models.BooleanField(default=False, verbose_name='HSH W'),
        ),
        migrations.AlterField(
            model_name='sklad',
            name='interne_cislo',
            field=models.IntegerField(null=True, verbose_name='Číslo karty'),
        ),
        migrations.AlterField(
            model_name='sklad',
            name='ipsen_ene',
            field=models.BooleanField(default=False, verbose_name='IPSEN ENE'),
        ),
        migrations.AlterField(
            model_name='sklad',
            name='ipsen_w',
            field=models.BooleanField(default=False, verbose_name='IPSEN W'),
        ),
        migrations.AlterField(
            model_name='sklad',
            name='jednotkova_cena_eur',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='EUR/jednotka'),
        ),
        migrations.AlterField(
            model_name='sklad',
            name='jednotky',
            field=models.CharField(choices=[('ks', 'kus'), ('kg', 'kilogram'), ('par', 'pár'), ('l', 'litr'), ('m', 'metr'), ('baleni', 'balení')], default='ks', max_length=10, verbose_name='Jednotky'),
        ),
        migrations.AlterField(
            model_name='sklad',
            name='kriticky_dil',
            field=models.BooleanField(default=False, verbose_name='Kritický díl'),
        ),
        migrations.AlterField(
            model_name='sklad',
            name='kw',
            field=models.BooleanField(default=False, verbose_name='KW'),
        ),
        migrations.AlterField(
            model_name='sklad',
            name='kw1',
            field=models.BooleanField(default=False, verbose_name='KW 1'),
        ),
        migrations.AlterField(
            model_name='sklad',
            name='kw2',
            field=models.BooleanField(default=False, verbose_name='KW 2'),
        ),
        migrations.AlterField(
            model_name='sklad',
            name='kw3',
            field=models.BooleanField(default=False, verbose_name='KW 3'),
        ),
        migrations.AlterField(
            model_name='sklad',
            name='lac_1',
            field=models.BooleanField(default=False, verbose_name='LAC 1'),
        ),
        migrations.AlterField(
            model_name='sklad',
            name='lac_2',
            field=models.BooleanField(default=False, verbose_name='LAC 2'),
        ),
        migrations.AlterField(
            model_name='sklad',
            name='mikrof',
            field=models.BooleanField(default=False, verbose_name='MIKROF'),
        ),
        migrations.AlterField(
            model_name='sklad',
            name='min_mnozstvi_ks',
            field=models.PositiveIntegerField(default=0, verbose_name='Minimum'),
        ),
        migrations.AlterField(
            model_name='sklad',
            name='mnozstvi_ks_m_l',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Množství'),
        ),
        migrations.AlterField(
            model_name='sklad',
            name='nazev_dilu',
            field=models.CharField(max_length=100, verbose_name='Název dílu'),
        ),
        migrations.AlterField(
            model_name='sklad',
            name='objednano',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Objednáno?'),
        ),
        migrations.AlterField(
            model_name='sklad',
            name='poznamka',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Poznámka'),
        ),
        migrations.AlterField(
            model_name='sklad',
            name='tq8',
            field=models.BooleanField(default=False, verbose_name='TQ8'),
        ),
        migrations.AlterField(
            model_name='sklad',
            name='tqf_xl1',
            field=models.BooleanField(default=False, verbose_name='TQF XL1'),
        ),
        migrations.AlterField(
            model_name='sklad',
            name='tqf_xl2',
            field=models.BooleanField(default=False, verbose_name='TQF XL2'),
        ),
        migrations.AlterField(
            model_name='sklad',
            name='ucetnictvi',
            field=models.BooleanField(default=True, verbose_name='Účetnictví'),
        ),
        migrations.AlterField(
            model_name='sklad',
            name='umisteni',
            field=models.CharField(max_length=25, verbose_name='Umístění'),
        ),
        migrations.AlterField(
            model_name='sklad',
            name='xl_ene1',
            field=models.BooleanField(default=False, verbose_name='XL ENE1'),
        ),
        migrations.AlterField(
            model_name='sklad',
            name='xl_ene2',
            field=models.BooleanField(default=False, verbose_name='XL ENE2'),
        ),
    ]
