# Generated by Django 5.0.6 on 2024-06-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hpm_sklad", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="pouzite_zarizeni",
            field=models.CharField(
                max_length=70, null=True, verbose_name="Pro zařízení"
            ),
        ),
        migrations.AlterField(
            model_name="historicalsklad",
            name="umisteni",
            field=models.CharField(max_length=25, null=True, verbose_name="Umístění"),
        ),
        migrations.AlterField(
            model_name="sklad",
            name="umisteni",
            field=models.CharField(max_length=25, null=True, verbose_name="Umístění"),
        ),
    ]
