# Generated by Django 5.0.6 on 2025-04-04 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hpm_sklad', '0002_historicalsklad_dac_historicalsklad_dac_xl1_2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalsklad',
            old_name='q8',
            new_name='tq8',
        ),
        migrations.RenameField(
            model_name='sklad',
            old_name='q8',
            new_name='tq8',
        ),
    ]
