# Generated by Django 5.0.4 on 2024-05-09 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hpm_sklad', '0002_alter_sklad_celkova_cena_eur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sklad',
            name='cislo_objednavky',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Číslo objednávky'),
        ),
        migrations.AlterField(
            model_name='sklad',
            name='dac_xl1_2',
            field=models.BooleanField(default=False, verbose_name='DAC XL1-2'),
        ),
    ]
