# Generated by Django 5.0.6 on 2024-06-10 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hpm_sklad", "0002_alter_auditlog_pouzite_zarizeni_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="varianty",
            name="id_dodavatele",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="hpm_sklad.dodavatele",
                verbose_name="ID dodavatele",
            ),
        ),
        migrations.AlterField(
            model_name="varianty",
            name="id_sklad",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="hpm_sklad.sklad",
                verbose_name="ID sklad",
            ),
        ),
        migrations.AlterModelTable(
            name="varianty",
            table=None,
        ),
    ]
