# Generated by Django 5.0.6 on 2024-06-10 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "hpm_sklad",
            "0003_alter_varianty_id_dodavatele_alter_varianty_id_sklad_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="varianty",
            name="cislo_varianty",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Číslo varianty"
            ),
        ),
        migrations.AlterField(
            model_name="varianty",
            name="id_dodavatele",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="varianty",
                to="hpm_sklad.dodavatele",
                verbose_name="ID dodavatele",
            ),
        ),
        migrations.AlterField(
            model_name="varianty",
            name="id_sklad",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="varianty",
                to="hpm_sklad.sklad",
                verbose_name="ID sklad",
            ),
        ),
    ]
