# Generated by Django 5.0.4 on 2024-05-09 18:08

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hpm_sklad', '0003_alter_sklad_cislo_objednavky_alter_sklad_dac_xl1_2'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', 'Příjem'), ('OUT', 'Výdej')], max_length=10)),
                ('quantity', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('spare_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hpm_sklad.sklad')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalSklad',
            fields=[
                ('evidencni_cislo', models.IntegerField(db_index=True, verbose_name='Evidenční číslo')),
                ('interne_cislo', models.IntegerField(null=True, verbose_name='Číslo karty')),
                ('objednano', models.CharField(blank=True, max_length=100, null=True, verbose_name='Objednáno?')),
                ('nazev_dilu', models.CharField(max_length=100, verbose_name='Název dílu')),
                ('min_mnozstvi_ks', models.PositiveIntegerField(default=0, verbose_name='Minimum')),
                ('mnozstvi_ks_m_l', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Množství')),
                ('jednotky', models.CharField(choices=[('ks', 'kus'), ('kg', 'kilogram'), ('par', 'pár'), ('l', 'litr'), ('m', 'metr'), ('baleni', 'balení')], default='ks', max_length=10, verbose_name='Jednotky')),
                ('umisteni', models.CharField(max_length=25, verbose_name='Umístění')),
                ('dodavatel', models.CharField(blank=True, max_length=70, null=True, verbose_name='Dodavatel')),
                ('datum_nakupu', models.DateField(blank=True, null=True, verbose_name='Datum nákupu')),
                ('cislo_objednavky', models.CharField(blank=True, max_length=20, null=True, verbose_name='Číslo objednávky')),
                ('jednotkova_cena_eur', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='EUR/jednotka')),
                ('celkova_cena_eur', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Celkem EUR')),
                ('poznamka', models.CharField(blank=True, max_length=200, null=True, verbose_name='Poznámka')),
                ('ucetnictvi', models.BooleanField(default=True, verbose_name='Účetnictví')),
                ('kriticky_dil', models.BooleanField(default=False, verbose_name='Kritický díl')),
                ('hsh', models.BooleanField(default=False, verbose_name='HSH')),
                ('tq8', models.BooleanField(default=False, verbose_name='TQ8')),
                ('tqf_xl1', models.BooleanField(default=False, verbose_name='TQF XL1')),
                ('tqf_xl2', models.BooleanField(default=False, verbose_name='TQF XL2')),
                ('dc_xl', models.BooleanField(default=False, verbose_name='DC XL')),
                ('dac_xl1_2', models.BooleanField(default=False, verbose_name='DAC XL1-2')),
                ('dl_xl', models.BooleanField(default=False, verbose_name='DL XL')),
                ('dac', models.BooleanField(default=False, verbose_name='DAC')),
                ('lac_1', models.BooleanField(default=False, verbose_name='LAC 1')),
                ('lac_2', models.BooleanField(default=False, verbose_name='LAC 2')),
                ('ipsen_ene', models.BooleanField(default=False, verbose_name='IPSEN ENE')),
                ('hsh_ene', models.BooleanField(default=False, verbose_name='HSH ENE')),
                ('xl_ene1', models.BooleanField(default=False, verbose_name='XL ENE1')),
                ('xl_ene2', models.BooleanField(default=False, verbose_name='XL ENE2')),
                ('ipsen_w', models.BooleanField(default=False, verbose_name='IPSEN W')),
                ('hsh_w', models.BooleanField(default=False, verbose_name='HSH W')),
                ('kw', models.BooleanField(default=False, verbose_name='KW')),
                ('kw1', models.BooleanField(default=False, verbose_name='KW 1')),
                ('kw2', models.BooleanField(default=False, verbose_name='KW 2')),
                ('kw3', models.BooleanField(default=False, verbose_name='KW 3')),
                ('mikrof', models.BooleanField(default=False, verbose_name='MIKROF')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical sklad',
                'verbose_name_plural': 'historical sklads',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
