# Generated by Django 5.0.4 on 2024-05-09 18:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hpm_sklad', '0004_auditlog_historicalsklad'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='datum_operace',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Datum pohybu'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Čas operace'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='movement_type',
            field=models.CharField(choices=[('IN', 'Příjem'), ('OUT', 'Výdej')], max_length=10, verbose_name='Typ operace'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Množství'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='spare_part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hpm_sklad.sklad', verbose_name='Skladová položka'),
        ),
    ]
