# Generated by Django 5.0.6 on 2024-07-03 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hpm_sklad', '0005_alter_varianty_id_dodavatele_alter_varianty_id_sklad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poptavky',
            name='varianty',
            field=models.ManyToManyField(through='hpm_sklad.PoptavkaVarianty', to='hpm_sklad.varianty'),
        ),
    ]
