# Generated by Django 5.0.6 on 2024-05-23 12:30

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hpm_sklad', '0005_auditlog_datum_operace_alter_auditlog_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dodavatele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dodavatel', models.CharField(max_length=100, verbose_name='Dodavatel')),
                ('kontakt', models.CharField(max_length=100, verbose_name='Kontaktní osoba')),
                ('email', models.EmailField(max_length=100, verbose_name='E-mail')),
                ('telefon', models.CharField(max_length=20, verbose_name='Telefon')),
                ('jazyk', models.CharField(choices=[('CZ', 'Český'), ('SK', 'Slovenský'), ('DE', 'Německý'), ('EN', 'Anglický')], default='CZ', max_length=2, verbose_name='Jazyk')),
            ],
        ),
        migrations.CreateModel(
            name='Zarizeni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zarizeni', models.CharField(max_length=10, verbose_name='Zařízení')),
                ('nazev_zarizeni', models.CharField(max_length=100, verbose_name='Název zařízení')),
                ('umisteni', models.CharField(max_length=20, verbose_name='Umístění')),
                ('typ_zarizeni', models.CharField(max_length=100, verbose_name='Typ zařízení')),
            ],
        ),
        migrations.RenameField(
            model_name='auditlog',
            old_name='movement_type',
            new_name='typ_operace',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='datum_operace',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='spare_part',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='cas_vytvoreni',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Čas vytvoření'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auditlog',
            name='celkova_cena_eur',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Celkem EUR'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='cislo_objednavky',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Číslo objednávky'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='datum_zmeny',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Datum změny'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auditlog',
            name='dodavatel',
            field=models.CharField(default='', max_length=70, verbose_name='Dodavatel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auditlog',
            name='evidencni_cislo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hpm_sklad.sklad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auditlog',
            name='interne_cislo',
            field=models.IntegerField(null=True, verbose_name='Číslo karty'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='jednotkova_cena_eur',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='EUR/jednotka'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='jednotky',
            field=models.CharField(choices=[('ks', 'kus'), ('kg', 'kilogram'), ('par', 'pár'), ('l', 'litr'), ('m', 'metr'), ('baleni', 'balení')], default='ks', max_length=10, verbose_name='Jednotky'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='mnozstvi_ks_m_l',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Množství'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='nazev_dilu',
            field=models.CharField(default='', max_length=100, verbose_name='Název dílu'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auditlog',
            name='objednano',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Objednáno?'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='operaci_provedl',
            field=models.CharField(default='', max_length=20, verbose_name='Operaci provedl'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auditlog',
            name='pouzite_zarizeni',
            field=models.CharField(default='', max_length=70, verbose_name='Dodavatel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auditlog',
            name='poznamka',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Poznámka'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='ucetnictvi',
            field=models.BooleanField(default=0, verbose_name='Účetnictví'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auditlog',
            name='umisteni',
            field=models.CharField(default='', max_length=25, verbose_name='Umístění'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auditlog',
            name='zmena_mnozstvi',
            field=models.PositiveIntegerField(default=0, verbose_name='Změna množství'),
            preserve_default=False,
        ),
    ]
