# Generated by Django 5.2.13 on 2026-05-11 10:18

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hpm_sklad', '0005_remove_historicalsklad_dac_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Skladové pohyby'},
        ),
        migrations.AlterModelOptions(
            name='poptavkavarianty',
            options={'verbose_name': 'Poptávka variant', 'verbose_name_plural': 'Poptávky variant'},
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='ucetnictvi',
            field=models.BooleanField(verbose_name='V účetnictví'),
        ),
        migrations.AlterField(
            model_name='dodavatele',
            name='dodavatel',
            field=models.CharField(max_length=100, verbose_name='Název dodavatele'),
        ),
        migrations.AlterField(
            model_name='historicalsklad',
            name='ucetnictvi',
            field=models.BooleanField(default=True, verbose_name='V účetnictví'),
        ),
        migrations.AlterField(
            model_name='sklad',
            name='ucetnictvi',
            field=models.BooleanField(default=True, verbose_name='V účetnictví'),
        ),
        migrations.AlterField(
            model_name='varianty',
            name='dodavatel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='varianty_dodavatele', to='hpm_sklad.dodavatele', verbose_name='Název dodavatele'),
        ),
        migrations.CreateModel(
            name='HistoricalAuditLog',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('ucetnictvi', models.BooleanField(verbose_name='V účetnictví')),
                ('interne_cislo', models.IntegerField(null=True, verbose_name='Číslo karty')),
                ('objednano', models.CharField(blank=True, max_length=100, null=True, verbose_name='Objednáno?')),
                ('nazev_dilu', models.CharField(db_index=True, max_length=100, verbose_name='Název dílu')),
                ('zmena_mnozstvi', models.IntegerField(verbose_name='Změna množství')),
                ('mnozstvi', models.PositiveIntegerField(verbose_name='Množství')),
                ('jednotky', models.CharField(choices=[('ks', 'kus'), ('kg', 'kilogram'), ('pár', 'pár'), ('l', 'litr'), ('m', 'metr'), ('balení', 'balení')], default='ks', max_length=10, verbose_name='Jednotky')),
                ('typ_operace', models.CharField(choices=[('PŘÍJEM', 'Příjem'), ('VÝDEJ', 'Výdej')], max_length=10, null=True, verbose_name='Typ operace')),
                ('pouzite_zarizeni', models.CharField(max_length=70, null=True, verbose_name='Pro zařízení')),
                ('umisteni', models.CharField(max_length=25, verbose_name='Umístění')),
                ('dodavatel', models.CharField(max_length=70, verbose_name='Dodavatel')),
                ('datum_vydeje', models.DateField(blank=True, null=True, verbose_name='Datum výdeje')),
                ('datum_nakupu', models.DateField(blank=True, null=True, verbose_name='Datum nákupu')),
                ('cislo_objednavky', models.CharField(blank=True, max_length=20, null=True, verbose_name='Číslo objednávky')),
                ('jednotkova_cena_eur', models.FloatField(default=0.0, verbose_name='EUR/jednotka')),
                ('celkova_cena_eur', models.FloatField(default=0.0, verbose_name='Celkem EUR')),
                ('cas_vytvoreni', models.DateTimeField(blank=True, editable=False, verbose_name='Čas vytvoření')),
                ('typ_udrzby', models.CharField(choices=[('Reaktivní', 'Reaktivní'), ('Preventivní', 'Preventivní'), ('Prediktivní', 'Prediktivní'), ('Inventura', 'Inventurní rozdíl')], max_length=20, null=True, verbose_name='Typ údržby')),
                ('poznamka', models.CharField(blank=True, max_length=200, null=True, verbose_name='Poznámka')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('evidencni_cislo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hpm_sklad.sklad', verbose_name='Evidenční číslo')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('operaci_provedl', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Operaci provedl')),
            ],
            options={
                'verbose_name': 'historical audit log',
                'verbose_name_plural': 'historical Skladové pohyby',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalVarianty',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nazev_varianty', models.CharField(max_length=255, verbose_name='Název varianty')),
                ('cislo_varianty', models.CharField(max_length=255, null=True, verbose_name='Číslo varianty')),
                ('jednotkova_cena_eur', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='EUR/jednotka')),
                ('dodaci_lhuta', models.PositiveIntegerField(verbose_name='Dodací lhůta')),
                ('min_obj_mnozstvi', models.PositiveIntegerField(verbose_name='Min. obj. množství')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('dodavatel', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hpm_sklad.dodavatele', verbose_name='Název dodavatele')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sklad', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hpm_sklad.sklad', verbose_name='Skladová položka')),
            ],
            options={
                'verbose_name': 'historical Varianta',
                'verbose_name_plural': 'historical Varianty',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
