# Generated by Django 5.0.6 on 2024-07-04 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hpm_sklad', '0006_poptavky_varianty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='varianty',
            old_name='id_dodavatele',
            new_name='dodavatel',
        ),
        migrations.RenameField(
            model_name='varianty',
            old_name='id_sklad',
            new_name='sklad',
        ),
    ]
