# Generated by Django 5.0.6 on 2024-05-23 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hpm_sklad', '0006_dodavatele_zarizeni_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dodavatele',
            name='email',
            field=models.EmailField(max_length=100, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='dodavatele',
            name='jazyk',
            field=models.CharField(choices=[('CZ', 'Český'), ('SK', 'Slovenský'), ('DE', 'Německý'), ('EN', 'Anglický')], default='CZ', max_length=2, null=True, verbose_name='Jazyk'),
        ),
        migrations.AlterField(
            model_name='dodavatele',
            name='kontakt',
            field=models.CharField(max_length=100, null=True, verbose_name='Kontaktní osoba'),
        ),
        migrations.AlterField(
            model_name='dodavatele',
            name='telefon',
            field=models.CharField(max_length=20, null=True, verbose_name='Telefon'),
        ),
    ]
