# Generated by Django 5.0.6 on 2024-05-23 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hpm_sklad', '0007_alter_dodavatele_email_alter_dodavatele_jazyk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='pouzite_zarizeni',
            field=models.CharField(max_length=70, verbose_name='Pro zařízení'),
        ),
    ]
