# Generated by Django 5.0.6 on 2024-05-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hpm_sklad', '0008_alter_auditlog_pouzite_zarizeni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsklad',
            name='evidencni_cislo',
            field=models.IntegerField(blank=True, db_index=True, verbose_name='Evidenční číslo'),
        ),
        migrations.AlterField(
            model_name='sklad',
            name='evidencni_cislo',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Evidenční číslo'),
        ),
    ]
