# Generated by Django 5.0.6 on 2025-01-28 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hpm_sklad", "0009_auditlog_typ_udrzby_alter_auditlog_jednotky_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Zarizeni",
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="typ_udrzby",
            field=models.CharField(
                choices=[
                    ("Reaktivní", "Reaktivní"),
                    ("Preventivní", "Preventivní"),
                    ("Prediktivní", "Prediktivní"),
                    ("Inventura", "Inventurní rozdíl"),
                ],
                max_length=20,
                null=True,
                verbose_name="Typ údržby",
            ),
        ),
    ]
