# Generated by Django 5.0.6 on 2025-03-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hpm_sklad", "0010_delete_zarizeni_alter_auditlog_typ_udrzby"),
    ]

    operations = [
        migrations.CreateModel(
            name="Zarizeni",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("zarizeni", models.CharField(max_length=10, verbose_name="Zařízení")),
                (
                    "nazev_zarizeni",
                    models.CharField(max_length=100, verbose_name="Název zařízení"),
                ),
                ("umisteni", models.CharField(max_length=20, verbose_name="Umístění")),
                (
                    "typ_zarizeni",
                    models.CharField(max_length=100, verbose_name="Typ zařízení"),
                ),
            ],
            options={
                "verbose_name_plural": "Zařízení",
            },
        ),
    ]
