# Generated by Django 5.0.6 on 2025-03-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hpm_sklad", "0011_zarizeni"),
    ]

    operations = [
        migrations.AddField(
            model_name="sklad",
            name="zarizeni",
            field=models.ManyToManyField(blank=True, to="hpm_sklad.zarizeni"),
        ),
    ]
