# Generated by Django 5.0.6 on 2024-06-03 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hpm_sklad', '0011_alter_auditlog_options_alter_dodavatele_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalsklad',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical sklad', 'verbose_name_plural': 'historical Skladové položky'},
        ),
        migrations.AlterModelOptions(
            name='sklad',
            options={'ordering': ['-evidencni_cislo'], 'verbose_name_plural': 'Skladové položky'},
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='operaci_provedl',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Operaci provedl'),
        ),
    ]
