# Generated by Django 5.0.6 on 2024-06-03 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hpm_sklad', '0012_alter_historicalsklad_options_alter_sklad_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='datum_zmeny',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='datum_nakupu',
            field=models.DateField(blank=True, null=True, verbose_name='Datum nákupu'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='datum_vydeje',
            field=models.DateField(blank=True, null=True, verbose_name='Datum výdeje'),
        ),
    ]
