# Generated by Django 5.0.6 on 2024-06-03 20:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "hpm_sklad",
            "0013_remove_auditlog_datum_zmeny_auditlog_datum_nakupu_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalsklad",
            name="datum_nakupu",
            field=models.DateField(
                blank=True,
                default=django.utils.timezone.now,
                null=True,
                verbose_name="Datum nákupu",
            ),
        ),
        migrations.AlterField(
            model_name="sklad",
            name="datum_nakupu",
            field=models.DateField(
                blank=True,
                default=django.utils.timezone.now,
                null=True,
                verbose_name="Datum nákupu",
            ),
        ),
    ]
