# Generated by Django 5.0.6 on 2024-06-04 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hpm_sklad', '0014_alter_historicalsklad_datum_nakupu_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditlog',
            old_name='mnozstvi_ks_m_l',
            new_name='mnozstvi',
        ),
        migrations.RenameField(
            model_name='historicalsklad',
            old_name='mnozstvi_ks_m_l',
            new_name='mnozstvi',
        ),
        migrations.RenameField(
            model_name='sklad',
            old_name='mnozstvi_ks_m_l',
            new_name='mnozstvi',
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='typ_operace',
            field=models.CharField(choices=[('PŘÍJEM', 'Příjem'), ('VÝDEJ', 'Výdej')], max_length=10, verbose_name='Typ operace'),
        ),
    ]
