# Generated by Django 5.0.6 on 2024-06-04 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hpm_sklad', '0015_rename_mnozstvi_ks_m_l_auditlog_mnozstvi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsklad',
            name='datum_nakupu',
            field=models.DateField(blank=True, null=True, verbose_name='Datum nákupu'),
        ),
        migrations.AlterField(
            model_name='sklad',
            name='datum_nakupu',
            field=models.DateField(blank=True, null=True, verbose_name='Datum nákupu'),
        ),
    ]
