# Generated by Django 5.0.6 on 2024-06-04 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hpm_sklad", "0016_alter_historicalsklad_datum_nakupu_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="celkova_cena_eur",
            field=models.FloatField(default=0.0, verbose_name="Celkem EUR"),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="jednotkova_cena_eur",
            field=models.FloatField(default=0.0, verbose_name="EUR/jednotka"),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="mnozstvi",
            field=models.PositiveIntegerField(verbose_name="Množství"),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="zmena_mnozstvi",
            field=models.IntegerField(verbose_name="Změna množství"),
        ),
        migrations.AlterField(
            model_name="historicalsklad",
            name="mnozstvi",
            field=models.PositiveIntegerField(default=0, verbose_name="Množství"),
        ),
        migrations.AlterField(
            model_name="sklad",
            name="mnozstvi",
            field=models.PositiveIntegerField(default=0, verbose_name="Množství"),
        ),
    ]
